### ISSUE TITLE
gateway网关启动报错，请大佬帮忙看下，谢谢, 报错截图如下，不知道啥原因

### ISSUE THREAD

**Issue by aozeyu** [GuoGuang/madao_service#108]
<img width="2530" alt="截屏2023-08-27 23 15 19" src="https://github.com/GuoGuang/madao_service/assets/55688386/1843d7fe-1a9c-4f72-add4-7c8696c119d7">

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jwtAuthenticationFilter' defined in file [/Users/yaozeyu/Desktop/madao_service/madao-common/target/classes/com/madao/utils/security/JwtAuthenticationFilter.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'tokenProvider' defined in file [/Users/yaozeyu/Desktop/madao_service/madao-common/target/classes/com/madao/utils/security/TokenProvider.class]: Failed to instantiate [com.madao.utils.security.TokenProvider]: Constructor threw exception
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:245)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1189)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)

@GuoGuang

**Comment by aozeyu** [comment]
是少了什么配置吗，也没有啊，配置中心我正常启动了

**Comment by aozeyu** [comment]
@GuoGuang

**Comment by aozeyu** [comment]
除了配置中心正常启动外，其他文章服务，也报和网关一样的错误😂 @GuoGuang

**Comment by GuoGuang** [comment]
你远端com.madao.secretKey没有配置。
我更新了一下文档，你看一下吧如果还不行我再帮你看看

**Comment by aozeyu** [comment]
<img width="1270" alt="截屏2023-08-28 19 42 04" src="https://github.com/GuoGuang/madao_service/assets/55688386/0e997a18-6225-418a-b91b-5a7cd1ccee6b">

这个密钥库是你那边的吗😂，我这边咋生成不了呢 
@GuoGuang

**Comment by aozeyu** [comment]
我按文档命令

**Comment by GuoGuang** [comment]
先执行这个
keytool -genkeypair -alias madaoo.com -keyalg RSA -dname "CN=Web Server,OU=China,O=www.youwebsite.im,L=ShangHai,S=ShangHai,C=China" -keypass madaoo.com -keystore madao.keystore -storepass madaoo.com

**Comment by aozeyu** [comment]
<img width="2549" alt="截屏2023-08-29 16 42 48" src="https://github.com/GuoGuang/madao_service/assets/55688386/0e2c4b6a-a912-4f0e-acca-a561ecc1fd6e">
@GuoGuang  还是不行😂，生成倒是没问题了，但是我把生成的密钥不管是放到bootstrap.yml 里面还是 application.yml里重启 gateway服务都是报和之前一样的错，麻烦指导一下是我配置的不对吗

**Comment by GuoGuang** [comment]
注意看文档描述第六条，是远端配置中心。不是具体的某个微服务里的配置

**Comment by aozeyu** [comment]
<img width="2470" alt="截屏2023-08-30 08 28 10" src="https://github.com/GuoGuang/madao_service/assets/55688386/670695be-a4e4-461d-be2f-be3718177ebc">
@GuoGuang  起来了 谢谢

**Comment by aozeyu** [comment]
但是为啥我登录报登录信息过期呢我看密码是对上的呢，数据库加密的 和我 在前端输入的123456 ，麻烦看下 ,图片如下 @GuoGuang 
<img width="828" alt="截屏2023-08-30 09 12 42" src="https://github.com/GuoGuang/madao_service/assets/55688386/d539e3b1-96b2-4e9d-bb23-51b19461a883">

**Comment by GuoGuang** [comment]
这种问题自行debug断点调试吧。
> 看一下服务启动时是否有报错提示，以及redis、mysql等配置是否正确

**Comment by aozeyu** [comment]
ok
